version: "3"
services:
    react-client:
        image: react-client
        build: ./front-end/letsmeet
        stdin_open: true
        ports:
            - "3000:3000"
        # networks:
        #     - letsmeet-network
        volumes:
            - ./front-end/letsmeet/:/usr/src/app # mounts local directory so any code changes is reflected without having to rebuild
            - /usr/src/app/node_modules # tells docker to ignore local node_modules
    express-server:
        image: express-server
        build: ./back-end/letsmeet
        ports:
            - "4000:4000"
        # networks:
        #     - letsmeet-network
        env_file: ./back-end/letsmeet/config/dev.env
        # depends_on:
        #     - mongo
        volumes:
            - ./back-end/letsmeet/:/usr/src/app 
            - /usr/src/app/node_modules
        # command: /usr/src/app/node_modules/.bin/nodemon server.js
    # mongo:
    #     image: mongo
    #     port:
    #         - "27017:27017"
    #     networks:
    #         - letsmeet-network
    #     volumes:
    #         - mongo-data:/data/db
# networks:
#     letsmeet-network:
#         driver: bridge
# volumes:
#     mongo-data:
#         driver: local