name: github-actions

on: [push]

env: 
  API_BASE_URL: ${{process.env.API_BASE_URL}}
  API_SECRET_KEY: ${{process.env.API_SECRET_KEY}}
  DB_USERNAME: ${{process.env.DB_USERNAME}}
  DB_PASSWORD: ${{process.env.DB_PASSWORD}}
  JWT_SECRET: ${{process.env.JWT_SECRET}}
  GMAIL: ${{process.env.GMAIL}}
  GMAIL_PASSWORD: ${{process.env.GMAIL_PASSWORD}}
  MONGO_URI: ${{process.env.MONGO_URI}}
  REACT_APP_BASE_URL: ${{process.env.REACT_APP_BASE_URL}}

jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test